export const stocksList = {
  ZM: 'Zoom',
  NVDA: 'NVIDIA',
  TSLA: 'Tesla',
  PYPL: 'PayPal',
  AAPL: 'Apple',
  FB: 'Facebook',
  PFE: 'Pfizer',
  BA: 'Boeing',
  BIDU: 'Baidu',
  WFC: 'Wells Fargo',
  CAT: 'Caterpillar',
  NFLX: 'Netflix',
  WMT: 'Walmart',
  AMZN: 'Amazon',
  INTC: 'Intel',
  MSFT: 'Microsoft',
  GOOG: 'Alphabet',
  NKE: 'Nike',
  GILD: 'Gilead',
  CRM: 'salesforce.com',
  JPM: 'JPMorgan',
  ABT: 'Abbott',
  MA: 'MasterCard',
  DIS: 'Walt Disney',
  JNJ: 'J & J',
  ADBE: 'Adobe',
  IBM: 'IBM',
  BAC: 'Bank Of America',
  MCD: "McDonald's",
  AVGO: 'Broadcom',
  QCOM: 'Qualcomm',
  BRK: 'B  	Berkshire Hathaway',
  BIIB: 'Biogen',
  VZ: 'Verizon',
  C: 'Citi Group',
  T: 'AT&T',
  BMY: 'Bristol Myers',
  GS: 'Goldman Sachs',
  KO: 'Coca Cola',
  MS: 'Morgan Stanley',
  NYSE: 'Colgate-Palmolive',
  GE: 'General Electric',
  V: 'Visa',
  MMM: '3M',
  COP: 'ConocoPhillips',
  MRK: 'Merck',
  CSCO: 'Cisco',
  SBUX: 'Starbucks',
  PM: 'Philip Morris',
  LMT: 'Lockheed Martin',
};
